### ISSUE TITLE
Not working with worlds containing "-"

### ISSUE THREAD

**Issue by zankia** [TheNewEconomy/TNE-Bukkit#120]
Hello,

My main world contains a dash `-` and it disallow me to load accounts.
Could you please change your separator in [Account.java](https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/src/com/github/tnerevival/account/Account.java#L59) on lines 59,67,78 to a more convenient one like `;`, for example ?

Thank you

**Comment by creatorfromhell** [comment]
Is there a reason that the world can't simply be written in camel case? Either way, changing the separate will have to wait until after 5.1 since there have been versions released already and it'll require convert the database.

**Comment by zankia** [comment]
No, there is no reason. But Multiverse allowed me to do it, so I did it 😋 
Don't worry about the time it takes, I'm not in a hurry.

**Comment by creatorfromhell** [comment]
Fixed in latest commit 8dc81693cf517a28c02690d25ea31716fdedc4fc.

Test Ran:

account data: world-example:Dollar,113723.21-world:Default,0.0-world:Default,0.0-world:Default,0.0-world--example:Dollar,113723.21-world----example:Dollar,113723.21

Balance of Dollar in world "world-example" is currently 113723.21.
Balance of Default in world "world" is currently 0.0.
Balance of Default in world "world" is currently 0.0.
Balance of Default in world "world" is currently 0.0.
Balance of Dollar in world "world--example" is currently 113723.21.
Balance of Dollar in world "world----example" is currently 113723.21.

**Comment by Carisus** [comment]
Wow, you rich.

**Comment by creatorfromhell** [comment]
Definitely rich with virtual currency!

**Comment by zankia** [comment]
Thank you, you're really efficient!

**Comment by creatorfromhell** [comment]
No problem, if you need further assistance I have created a discord server for TNE today, which will be the fastest way to get a response. https://discord.gg/WNdwzpy
