### ISSUE TITLE
Have infinite money

### ISSUE THREAD

**Issue by Hanarion** [TheNewEconomy/TNE-Bukkit#216]
Hey, i've found a problem, when i do /pay myname amount it's like i give me the amount :/
there is a screen : [http://cloud.hanarion.fr/screen/22-23-33_2018-06-04.png](url)

**Comment by creatorfromhell** [comment]
Which version of TNE are you currently using? I've tried this under the currenlty supported version, which is Beta 1.0, and everything works as planned. http://prntscr.com/jquu4t

**Comment by Hanarion** [comment]
The last, idk why but I've also the baltop command Wich aren't working, I've already reinstalled the plugin but it looks the same :/

**Comment by creatorfromhell** [comment]
I've tested it and it works as expected. AS far as the baltop issue you haven't really explained how it's not working, simply stating "it doesn't work" doesn't help me figure out the issue, which is why there is a report format that you elected not to follow. Closing until the proper format is used.
