### ISSUE TITLE
MySQL Suggestion

### ISSUE THREAD

**Issue by Carisus** [TheNewEconomy/TNE-Bukkit#58]
**Suggestion / enhancement**

Would it be possible to add something in the MySQL DB that notes the name of the server? This is to make the plugin more BungeeCord friendly. As of right now if MySQL is used accounts are the same across all servers unless told not to use the MySQL. There are ways I can get around this, sending it to a separate DB, use flat file and the like. But it would be easier for me if you had the option somewhere to note the server name. Or however you want to do it.

**Comment by creatorfromhell** [comment]
I could most likely include it as a new field for accounts. I'm just curious if it'd be easier to use the server's IP or name. I'm not familiar with bungeecord so you most likely have more insight on which is more useful.

**Comment by Carisus** [comment]
First, I am not a developer, I can read JAVA and figure out where the author was going but I can't write it myself. That said, there are a couple ways I have seen it done. 

One way is to ask the server what its [name](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Bukkit.html#getServerName) is. And use that the same way you use [world](https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/src/com/github/tnerevival/core/configurations/MainConfiguration.java#L10). Adding whether the user wants to track the server name in the config for bungee compatibility. 

The other way is to ask in the config what the name of the server is, what they put in there doesn't matter. This way they can use the same name to have economies go cross server. This has the potential to cause a race condition when using multi-player banks though. depending on how you implement it.

To answer the question you actually asked, I would use server names, not IP. Some servers are on the same IP with different ports. Even BungeeCord separates them by name in the config.

**Comment by creatorfromhell** [comment]
The only issue with cross-server compatibility would be the fact nothing gets saved until the auto-save system triggers it or the server shuts down. So the new multi-player bank system, and shop systems have the potential to cause issues. A few instances:

Multi-player Banks:
Player "Test" withdraws two diamond blocks. TNE then saves it internally to the owner's account. Player "Test 2" proceeds to withdraw two diamond blocks before the auto-save task is run, this has now successfully duped two diamond blocks. This could be prevented from saving to MySQL on bank close, but at the cost of performance for larger servers.

Shop Systems:
Player "Test" has a shop in World1, but is currently purchasing items/having the time of their life in World2. Let's say someone buys something from his shop which is added to his balance in World1. This now has the added effect to either make his balance greater or less than what it should be. This could be prevented by just adding all profits to shop's data, but then you'd have to take into consideration that shops that buy items will now be required to store money to buy said items. The player would also then have to run a command/visit the shop to collect their earnings now too.

This could be fixed by creating a table for tracking updates that need to be made to data, but then you'd need to poll this table every so often, at which point you start looking into just lowering the auto save period, which would decrease performance.

**Comment by Carisus** [comment]
Oh, I thought you were doing direct to MySQL transactions. I didn't know you were saving them to ram first. That sounds like a bad idea. Why not just go straight to the DB? That way it is just first come first serve no matter what. This would also help keep the ram load low and prevent the server from running out of ram. This is what MySQL was written for, thousands of connections a second, even on a modest computer. Every time a player attempts a transaction, open a connection, update the table, close the connection. Only one connection to that table allowed at a time. The proper way to do it would be to leave the connection open, but Minecraft screws that up with hacked in code. (Not Spigots fault they had to do it that way.)

**Comment by creatorfromhell** [comment]
If we didn't store TNE's account data to the account map then for every little thing I would have to query MySQL. This includes checking to see if a player has X amount, removing X amount checking to see if a player has a bank, getting the bank items, etc, which would ultimately impact performance.

**Comment by Carisus** [comment]
I don't think it would impact it in any way. It seems to me that if you are asking the account map or MySQL you are still asking, so that point is moot. Storing everything in ram takes up ram space, which would impact performance. But I am getting my information from a Database Guru, so it could be a little biased.

**Comment by creatorfromhell** [comment]
See the edit to the last reply. "EDIT: Forgot to specify, this is the PREFERRED way to do it when you also incorporate the FlatFile option. Once I also add a NoSQL option and ultimately eliminate FlatFile saving all together, then modifying the DB directly would be the best option." Short term it should be fine until a NoSQL format is implemented.

**Comment by Carisus** [comment]
You are correct that it is the best way to do it when it is going to Flat File. But it is waste (and possibly creates race conditions) on an SQL DB.
