### ISSUE TITLE
Pins

### ISSUE THREAD

**Issue by Carisus** [TheNewEconomy/TNE-Bukkit#67]
What is the [/pin set](https://github.com/TheNewEconomy/TNE-Bukkit/blob/9c451ea32ad71ef75acaa2ae42cda73f7a3c675b/src/com/github/tnerevival/commands/pin/PinSetCommand.java#L32) command and is there a way to not require it? 

Also, the perm isn't listed anywhere. It only took a second to find it, but may bother other users.

**Comment by creatorfromhell** [comment]
/pin set is TNE's way to enforce some form of account security, especially on offline servers. Pins are required to be confirmed before any action that involves money of any sort. 

They are currently required no matter what, but after reading this I am currently changing that so please hold for Alpha 3.1 in a few moments(up to an hour from now).

As for the permission node not being listed, I'll be updating the wiki tomorrow since Alpha 3.0 changed a lot of the internals.

**Comment by Carisus** [comment]
Thank you. I will let you close this when you want.
